### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by watermarkhu** [watermarkhu/OpenSurfaceSim#10]

**Comment by watermarkhu** [comment]
Add status badges

**Comment by watermarkhu** [comment]
Address #4 and #15 when solving this issue.

**Comment by watermarkhu** [comment]
#20

**Comment by Lolcroc** [comment]
`run_oopsc.py` no longer exists. Please update the Usage simulation section

**Comment by watermarkhu** [comment]
> `run_oopsc.py` no longer exists. Please update the Usage simulation section

I've updated the readme. There are other changes planned, which are also added to the readme.

**Comment by watermarkhu** [comment]
New instructions via #26
