### ISSUE TITLE
Add my binder integration

### ISSUE THREAD

**Issue by nathanshammah** [watermarkhu/OpenSurfaceSim#15]
Adding a My Binder badge in the Readme file will allow prospective users to try out the software without installing anything locally. I tried it and it works, thanks to the new package structure, with the `requirements.txt` file in the topmost folder. 

Pasting this in README.md should suffice:
[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/watermarkhu/OpenSurfaceSim/master)
(this is how it looks like: `[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/watermarkhu/OpenSurfaceSim/master)`)

To be most effective, the My Binder link could point directly to a tutorial, e.g. in the form of a Jupyter notebook, or to a script (using Jupyter Labs as My Binder default). Happy to help in this with PR or feedback along the way.

**Comment by watermarkhu** [comment]
Done in #30
