### ISSUE TITLE
License

### ISSUE THREAD

**Issue by watermarkhu** [watermarkhu/OpenSurfaceSim#4]
Properly reference [Blossom5](https://pub.ist.ac.at/~vnk/software.html) and Python integration.
Address license issues

**Comment by nathanshammah** [comment]
While the peculiar situation is being addressed, I'd still "protect" your code with the intended license. You could add a disclaimer in the Readme file, under a License section, pointing to the License template file you choose (e.g., new BSD 3.0) and remarking that Blossom5 is under another license.

**Comment by watermarkhu** [comment]
Section added to README in #17 pointing to the extra license.

**Comment by watermarkhu** [comment]
BlossomV should not be packaged with OpenSurfaceSim. Instead, the user should download the C package. This can be done in an assisted way through an automated script, in which case we need to make sure to list BlossomV's license before anything is downloaded. Our own interface with BlossomV can be written with [Pybind11](https://pybind11.readthedocs.io/en/master/).

**Comment by watermarkhu** [comment]
Solved in #26 

No uses function to download and compile blossom V.
